In [1]:
import requests
import numpy as np
import pandas as pd
from taipy import Core,Gui, DataNode
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select, WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from seleniumbase import Driver
from selenium.common.exceptions import NoSuchElementException,TimeoutException
import os
import time

In [29]:
def scrap(username, password):
    driver = Driver(uc=True)
    try:
        driver.get('https://viu.to/login')
        username = username
        password = password
        # Wait for login elements to be available and enter credentials
        WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="signin-username"]')))
        driver.find_element(By.XPATH, '//*[@id="signin-username"]').send_keys(username)
        driver.find_element(By.XPATH, '//*[@id="signin-password"]').send_keys(password)
        driver.find_element(By.XPATH, '//*[@id="content"]/form/p[5]/input').send_keys(Keys.ENTER)

        #redirect to a page
        driver.get('https://viu.to/user/continuewatching')
        #change the option from 3 months to beginning of time

        # Wait for the dropdown to load and change the option
        WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="content"]/div[1]/div[2]/select')))
        select = Select(driver.find_element(By.XPATH, '//*[@id="content"]/div[1]/div[2]/select'))
        select.select_by_visible_text('Beginning of time')

        webdriverwait = WebDriverWait(driver, 60)
        # Wait for the page to load
        webdriverwait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, '#content_results > div')))
        results = driver.find_elements(By.CSS_SELECTOR, '#content_results > div')
        # Extract text data from each result element
        data = []
        for result in results:
            try:
                information = result.find_element(By.XPATH, './div[2]').text  # Use relative XPath for robustness
                data.append(information)
            except NoSuchElementException:
                continue  # If an element is not found, skip to the next  # If an element is not found, skip to the next

        v = pd.DataFrame(data, columns=['Information'])

        v[['Title','Rating','Year']] = v['Information'].str.split('\n',expand=True)

        v.drop(columns=['Rating','Year','Information'],inplace=True)
    except(NoSuchElementException,TimeoutException) as e:
        print(f"An error occurred: {e}")
    finally:
        driver.get('viu.to/logout')
        driver.quit()

In [ ]:
def mb_scrap(): #Regardless of how I scrap the time will always be 4 minutes, this might be due to how the website is designed. 
# Initialize the WebDriver
    driver = Driver(uc=True)

    try:
        driver.get('https://www.movieboxpro.app/index/login/code_login')
        print('Check the mobile application for the login code')
        time.sleep(20)  # Wait for manual login or other conditions

        driver.get('https://www.movieboxpro.app/index/index/my_box?watched=1')
        data = []
        is_first_page = True  # To track whether we are on the first page

        while True:
            try:
                # Wait for the elements to load
                WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, '/html/body/div/div/div[6]/div[3]')))

                # Increment the div index to move to the next element
                div_index = 1
                while True:
                    try:
                        dynamic_xpath = f'/html/body/div/div/div[6]/div[3]/div[{div_index}]/a/div/div[2]/p[3]'
                        element = driver.find_element(By.XPATH, dynamic_xpath)
                        element_text = element.text

                        # Check if the element's text is already in the data list
                        if element_text not in data:
                            data.append(element_text)
                        else:
                            print(f"Duplicate found, skipping: {element_text}")
                        div_index += 1
                    except NoSuchElementException:
                        break

                # Determine which "Next" button to use
                if is_first_page:
                    # Look for the "Next" button for the first page
                    try:
                        next_button = driver.find_element(By.XPATH, '//*[@id="page"]/ul/li/a')
                        is_first_page = False  # After the first page, switch to the subsequent pages logic
                    except NoSuchElementException:
                        print("No 'Next' button found on the first page. Exiting...")
                        break
                else:
                    # Look for the "Next" button for subsequent pages
                    try:
                        next_button = driver.find_element(By.XPATH, '//*[@id="page"]/ul/li[2]/a')
                    except NoSuchElementException:
                        print("No more pages to scrape. Exiting...")
                        break

                # Click the "Next" button and wait for the page to reload
                next_button.click()
                WebDriverWait(driver, 20).until(EC.staleness_of(next_button))

            except TimeoutException:
                print('Timed out waiting for elements to load')
                break
            m= pd.DataFrame(data,columns=['Title'])
            #Drop the first row
            m = m.iloc[1:]

    except (NoSuchElementException, TimeoutException) as e:
        print(f"An error occurred: {e}")
    finally:

        driver.quit()

In [7]:
def anime():
    driver = Driver(uc=True)
    driver.get('https://myanimelist.net/animelist/Tjkill3r?status=7')
    data = []


    for i in range(2,175):
        xpath = '//*[@id="list-container"]/div[4]/div/table/tbody['+str(i)+']/tr[1]/td[4]/a'
        elements = driver.find_element(By.XPATH,xpath)
        data.append(elements.text)
    driver.quit()

    a = pd.DataFrame(data, columns=['Title'])
    return a.head()

In [8]:
anime()

c:\Users\tedjo\anaconda3\envs\frontend\Lib\subprocess.py:1127: ResourceWarning: subprocess 22592 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\tedjo\AppData\Roaming\Python\Python312\site-packages\pandas\_config\config.py:639: ResourceWarning: unclosed file <_io.FileIO name=5 mode='wb' closefd=True>
  cursor = cursor[p]
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\tedjo\AppData\Roaming\Python\Python312\site-packages\pandas\_config\config.py:639: ResourceWarning: unclosed file <_io.FileIO name=6 mode='rb' closefd=True>
  cursor = cursor[p]
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\tedjo\AppData\Roaming\Python\Python312\site-packages\pandas\_config\config.py:639: ResourceWarning: unclosed file <_io.FileIO name=7 mode='rb' closefd=True>
  cursor = cursor[p]
ResourceWarning: Enable tracemalloc to get the object allocation traceback

                        Title
0  Food Wars! The Third Plate
1                    Golgo 13
2               Hinomaru Sumo
3                 Kaiju No. 8
4                   Lupin III

In [9]:
def get_content_details(content_name, api_key=None):
    """
    Fetch detailed information about a movie or TV show from the TMDB API, including cast and crew details.

    Args:
    content_name (str): The name of the movie or TV show to search for.
    api_key (str): The API key for the TMDB API. If not provided, will look for an environment variable.

    Returns:
    dict: A dictionary containing detailed information about the content, including cast and crew.
    """
    # Check API key
    api_key = api_key or os.getenv('TMDB_API_KEY')
    if not api_key:
        raise ValueError("API key is required. Set it as an argument or an environment variable 'TMDB_API_KEY'.")

    # Base URL for the API
    base_url = "https://api.themoviedb.org/3"

    try:
        # Fetch genre details for TV shows and movies
        tv_genre_url = f"{base_url}/genre/tv/list?api_key={api_key}"
        tv_genre_response = requests.get(tv_genre_url)
        tv_genre_response.raise_for_status()
        tv_genre_data = tv_genre_response.json()
        tv_genres = {genre['id']: genre['name'] for genre in tv_genre_data.get('genres', [])}

        movies_genre_url = f"{base_url}/genre/movie/list?api_key={api_key}"
        movies_genre_response = requests.get(movies_genre_url)
        movies_genre_response.raise_for_status()
        movies_genre_data = movies_genre_response.json()
        movie_genres = {genre['id']: genre['name'] for genre in movies_genre_data.get('genres', [])}

        # Search for the content
        search_url = f"{base_url}/search/multi?api_key={api_key}&query={content_name}"
        search_response = requests.get(search_url)
        search_response.raise_for_status()
        search_data = search_response.json()

        # Check if the search results are not empty
        if not search_data['results']:
            return {'Error': 'No content found with the provided title.'}

        # Get the most relevant result
        first_result = search_data['results'][0]
        content_id = first_result.get('id')
        content_type = first_result.get('media_type', 'N/A')

        # Determine the appropriate genre list
        genres = tv_genres if content_type == 'tv' else movie_genres
        content_genres = [genres.get(genre_id, 'Unknown') for genre_id in first_result.get('genre_ids', [])]

        # Fetch additional details, trailers, and recommendations
        details_url = f"{base_url}/{content_type}/{content_id}?api_key={api_key}"
        trailer_url = f"{base_url}/{content_type}/{content_id}/videos?api_key={api_key}"
        reviews_url = f"{base_url}/{content_type}/{content_id}/reviews?api_key={api_key}"
        recommendations_url = f"{base_url}/{content_type}/{content_id}/recommendations?api_key={api_key}"
        credits_url = f'{base_url}/{content_type}/{content_id}/credits?api_key={api_key}'  # Credits endpoint for cast and crew

        details_response = requests.get(details_url)
        trailer_response = requests.get(trailer_url)
        reviews_response = requests.get(reviews_url)
        recommendations_response = requests.get(recommendations_url)
        credits_response = requests.get(credits_url)

        details_response.raise_for_status()
        trailer_response.raise_for_status()
        reviews_response.raise_for_status()
        recommendations_response.raise_for_status()
        credits_response.raise_for_status()

        # Process additional data
        content_infos = details_response.json()
        trailer_data = trailer_response.json()
        reviews_data = reviews_response.json()
        recommendations_data = recommendations_response.json()
        credits_data = credits_response.json()

        # Extract cast and crew information
        cast_info = [
            {'Name': cast_member.get('name'), 'Character': cast_member.get('character'), 'Profile Path': cast_member.get('profile_path')}
            for cast_member in credits_data.get('cast', [])[:10]  # Limit to top 10 cast members
        ]

        crew_info = [
            {'Name': crew_member.get('name'), 'Job': crew_member.get('job'), 'Department': crew_member.get('department'),'Profile Path': crew_member.get('profile_path')}
            for crew_member in credits_data.get('crew', []) if crew_member.get('department') in ['Directing', 'Writing', 'Production']
        ]

        # Find the most relevant trailer
        trailer_key = next((trailer.get('key') for trailer in trailer_data.get('results', []) if trailer.get('type') == 'Trailer' and 'official' in trailer.get('name', '').lower()), 'N/A')
        trailer_link = f"https://www.youtube.com/watch?v={trailer_key}" if trailer_key != 'N/A' else 'N/A'

        # Extract reviews
        top_reviews = [review.get('content', 'No content') for review in reviews_data.get('results', [])[:10]]

        # Extract recommendations
        recommendations_info = [{
            'Title': rec.get('name') if rec.get('media_type') == 'tv' else rec.get('title'),
            'Poster': rec.get('poster_path'),
            'Content ID': rec.get('id')
        } for rec in recommendations_data.get('results', [])]

        # Determine runtime and origin country
        if content_type == 'tv':
            runtime = content_infos.get('episode_run_time', [])
            runtime = runtime[0] if runtime else None  # Get the first runtime if available
            origin_country = content_infos.get('origin_country', ['N/A'])[0]  # Get the first origin country
            num_episodes = content_infos.get('number_of_episodes', None)
        else:
            runtime = content_infos.get('runtime', 'N/A')
            origin_country = next((company.get('origin_country') for company in content_infos.get('production_companies', [])), 'N/A')
            num_episodes = 1  # For movies, set the number of episodes to 1

        # Construct the final content details
        content_info = {
            'Title': first_result.get('name') if content_type == 'tv' else first_result.get('title'),
            'Content ID': content_id,
            'Type': content_type,
            'Poster': first_result.get('poster_path'),
            'Backdrop': first_result.get('backdrop_path'),
            'Overview': first_result.get('overview'),
            'Trailer': trailer_link,
            'Genres': ', '.join(content_genres),
            'Runtime (minutes)': runtime,
            'Number of Episodes': num_episodes,
            'Rating': round(first_result.get('vote_average', 0), 2),
            'Release Year': first_result.get('first_air_date' if content_type == 'tv' else 'release_date', 'N/A'),
            'Origin Country': origin_country,
            'Reviews': top_reviews,
            'Recommendations': recommendations_info,
            'Cast': cast_info,
            'Crew': crew_info
        }

        return content_info


    except requests.exceptions.RequestException as e:
        return {'Error': f"Failed to fetch content details: {e}"}

In [19]:
data = get_content_details('Dune Part 2', "9121de210a58fbaa7cd5f0654a7ec8d9")

data

{'Title': 'Dune: Part Two',
 'Content ID': 693134,
 'Type': 'movie',
 'Poster': '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
 'Backdrop': '/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
 'Overview': 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.',
 'Trailer': 'https://www.youtube.com/watch?v=U2Qp5pL3ovA',
 'Genres': 'Science Fiction, Adventure',
 'Runtime (minutes)': 167,
 'Number of Episodes': 1,
 'Rating': 8.16,
 'Release Year': '2024-02-27',
 'Origin Country': 'US',
 'Reviews': ['FULL SPOILER-FREE REVIEW @ https://talkingfilms.net/dune-part-two-review-the-new-generational-epitome-of-sci-fi-epics/\r\n\r\n"Dune: Part Two surpasses even the highest expectations, establishing itself as an unquestionable technical masterpiece of blockbuster filmmaking.\r\n\r\nWith a narrative that deepens the complex web of political relationships, power, faith, love, and destiny, it not only provides a breathtaking audiovisual spectacle, thanks to the genius of Denis Villeneuve, Greig Fraser, and Hans Zimmer, but it also offers a profound meditation on universal human themes through thematically rich world-building and thoroughly developed characters. The superb performances of the entire cast, led by a career-best Timothée Chalamet and a mesmerizing Zendaya, further elevate this incredibly immersive cinematic experience.\r\n\r\nIt warrants comparisons with the greatest sequels in history, easily becoming the new generational epitome of sci-fi epics."\r\n\r\nRating: A+',
  "As anticipated, a thrilling watch!\r\n\r\nI enjoyed <em>'Dune'</em>, though remember thinking it was obviously a complete set-up to a sequel and that this would only improve upon its predecessor - and that's very much the case. <em>'Dune: Part Two'</em> is excellent! My interest did wane slightly at roughly the middle part, as was similarly the case with the first film in truth, but that was a feeling that only lasted for a relativiely short time.\r\n\r\nAll in all, it's fantastic. The acting is top notch, the visuals are breathtaking <em>(those sandworms tho)</em> and the score is outstandingly hefty - you can always rely on the great Hans Zimmer! Timothée Chalamet stars yet again, as do the likes of Rebecca Ferguson, Zendaya, Dave Bautista & Co. The person I actually enjoyed most on screen was Javier Bardem, who is truly brilliant throughout. \r\n\r\nBring on <em>'Dune Messiah'</em>! On that note, happy to read that director Denis Villeneuve has noted that he won't be rushing that one out - and rightly so!",
  'This is certainly a great looking film to see on a big screen with some really effective, almost industrially sounding, audio - but what happened to the story? It\'s wafer thin and really stretched out for 2¾ hours. We pick up with "Paul" (Timothée Chalamet) and his mother (Rebecca Ferguson) trying to convince the "Fremen" that they are worth the hassle. Fortunately, leader "Stilgar" (Javier Bardem) is convinced of the messianic state of the young refugee, whilst their own reverend mother is on her last legs which might give "Jessica" a chance to prove her own worth, and provide an opportunity to peddle some embellished mythology about her son\'s ascendant propheteering. All of this manoeuvring and politicking is having quite an impact on "Chani" (the under-used Zendaya) and on the relationship between her and the increasingly worshipped new Duke. Meantime, now fully reinvigorated and emerged from his bath of recuperative Guinness, the evil "Baron Harkonnen" (an almost Zeppelin-like Stellan Skarsgård) has recruited his lethal nephew "Feyd-Rautha" (Austin Butler) to get to grips with the rebellion on "Arrakis" that is bringing him into the gaze of an ill-satisfied emperor (Christopher Walken). Battle lines are drawn! Now whilst I did enjoy this, the rest of the film is a gloriously photographed but slowly paced hybrid of "Khartoum" (1966) and "Lawrence of Arabia" (1962) with a bit of the "Phantom Menace" (1999) thrown in for good measure. The acting is adequate but the characterisations are all too routinely sacrificed at the altar of the stunning visuals and from about an hour to go, I was convinced this this was but part two of three (or maybe even more). Walken and Charlotte Rampling feature all too sparingly to make much difference, indeed even Zendaya\'s warrior-like tendencies seem to have been neutered rather and I though that Chalamet just tried far too hard to imbue his character with a strength that he was far more successful with first time round. That said, it does work well enough as a classy and well produced sci-fi adventure with plenty of action and mysticism but I needed more meat on it\'s bones. I still get distinctly squeamish when I watch what they do with the water, let alone where they get it from!!',
  'An absolutely mesmerizing masterpiece, breathtaking cinematography and a spellbinding soundtrack that elevate the viewing experience to unparalleled heights. It serves as a testament to the brilliance of the book series, standing as the pinnacle of sci-fi cinema history. Thanks, Villeneuve!',
  'Great but a little long. Sexier than LotR and no hair. Yell acting. Jabba bathes in black goo and kills women horribly. Walken is hilarious. Zendaya still an addict. Bridges is a bit self-serious. Amazing visuals. Really enjoyed...was glad and a bit bored by the end. Shorter Dunes please.',
  'Saw it on the bigger screen, which was worth it. The worms were quite large. The movie has a great way of passing across the grand scale of the world in a way that michael bay can never understand how to do with his robots movies.\r\n\r\nIt did stretch on quite a bit, looking back not even sure where all the three hours went. Its just all shaping up for the big battle with a bit of political intrigue here and there. Also, still have no idea how they get off the worms or how they load up large groups of people onto the worms, like, can they stop the worms whenever they want and let people climb on, and then giddy up, but if thats the case why dont they have stabled worms ready to go.',
  "I had to watch Dune part 1 because if I didn't, I would not have known what to expect in Dune part 2. The movie was incredible. To see it on the big screen really makes a difference. You need to see every angle possible. I understand why it needed to be that way. I loved the movie. I would watch Dune 1 and 2 over again. I didn't like the scene where Feyd-Rautha died. But it was necessry if they planned on doing a third installment for Dune. The casting for this film was picked brilliantly. It fit them like they were part of the era of Dune itself.",
  "**Not bad**\r\n\r\nOverall, a nice movie.\r\n\r\nBut it was not something extraordinary. The acting and direction were pretty average. There were a lot of editing mistakes. In some scenes, you feel like it was rushed. Some scenes feel like they are missing context. Some scenes are unnecessarily slow-paced.\r\n\r\nThere were a lot of stupid and logical fallacies. First, they show how dangerous those 'worms' are and run for life. Then they show you can actually 'tame' them like a cowboy, but with immense difficulty. Then you see the whole clan with tents, food, luggage, etc., riding them for traveling. I literally couldn't hold my laughter.\r\n\r\nWell, in the end, I was entertained.\r\n\r\nRating: 7/10",
  "I remember the first film, no not the first in this contemporary series but the first attempt to bring the books, to cinema. \r\n\r\nIn terms of contextual cohesiveness and pacing I feel it did a better job, than its latter day counterpart. I believe with this effort they are going for sweeping epic but somehow it comes across as inexplicably pedestrian.\r\n\r\nYes cinematography is remarkable, as are CGI effects but the pacing is slow and things happen that don't come together all that well or give the sense that they are contributing, meaningfully, to the overall story. Acting is competent but again, its not remarkable, which I think is in part down to a lack of depth, in characterisations.\r\n\r\nI know this review probably wont be popular or reflective of the mainstream but I sense they are trying to do too much and as a consequence, achieving too little.\r\n\r\nIn summary, visually compelling but lacking in a certain intensity and depth. Feels contextually spare and at times redundant, if that makes sense. Still worth a look if you liked the books.",
  "First of all, it just got dark when paul called out chani's rival princess :))\r\nFunny though! The blue thing that they called they called WATER OF LIFE is just so mysterious,,it literally controls them i suppose! I literally enjoyed that part when chani slapped paul after being consious :))) also paul is a whole bloodline bearer ig while the harkonnens are just gay :.>\r\nAlso the war parts were amazing. waiting for next part!!!"],
 'Recommendations': [{'Title': 'Dune',
   'Poster': '/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
   'Content ID': 438631},
  {'Title': 'Kung Fu Panda 4',
   'Poster': '/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg',
   'Content ID': 1011985},
  {'Title': 'Rebel Moon - Part Two: The Scargiver',
   'Poster': '/95gnJZIk2rEkMO0Ch46x5CVjnms.jpg',
   'Content ID': 934632},
  {'Title': 'Damsel',
   'Poster': '/AgHbB9DCE9aE57zkHjSmseszh6e.jpg',
   'Content ID': 763215},
  {'Title': 'Poor Things',
   'Poster': '/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg',
   'Content ID': 792307},
  {'Title': 'Madame Web',
   'Poster': '/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg',
   'Content ID': 634492},
  {'Title': 'Road House',
   'Poster': '/lwPsIgh98Wnpvkr3svkZwlhDrfm.jpg',
   'Content ID': 359410},
  {'Title': 'Ghostbusters: Frozen Empire',
   'Poster': '/e1J2oNzSBdou01sUvriVuoYp0pJ.jpg',
   'Content ID': 967847},
  {'Title': 'Dune',
   'Poster': '/ldugBX89jCQA9RRwfzRgX0gNpBc.jpg',
   'Content ID': 841},
  {'Title': 'Godzilla x Kong: The New Empire',
   'Poster': '/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg',
   'Content ID': 823464},
  {'Title': 'Late Night with the Devil',
   'Poster': '/jGY62i0D0zitaGz4Ema7vTEYIXw.jpg',
   'Content ID': 938614},
  {'Title': 'American Fiction',
   'Poster': '/57MFWGHarg9jid7yfDTka4RmcMU.jpg',
   'Content ID': 1056360},
  {'Title': 'The Zone of Interest',
   'Poster': '/hUu9zyZmDd8VZegKi1iK1Vk0RYS.jpg',
   'Content ID': 467244},
  {'Title': 'Spaceman',
   'Poster': '/f46WvKEsBn98WJbPJcO47ZoKn6B.jpg',
   'Content ID': 636706},
  {'Title': 'Godzilla Minus One',
   'Poster': '/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg',
   'Content ID': 940721},
  {'Title': 'Challengers',
   'Poster': '/H6vke7zGiuLsz4v4RPeReb9rsv.jpg',
   'Content ID': 937287},
  {'Title': 'Anatomy of a Fall',
   'Poster': '/kQs6keheMwCxJxrzV83VUwFtHkB.jpg',
   'Content ID': 915935},
  {'Title': 'Civil War',
   'Poster': '/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
   'Content ID': 929590},
  {'Title': 'Oppenheimer',
   'Poster': '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
   'Content ID': 872585},
  {'Title': 'Ricky Stanicky',
   'Poster': '/cEuX73Q1wpMypB1cr4l3MoMGpL4.jpg',
   'Content ID': 1022690}],
 'Cast': [{'Name': 'Timothée Chalamet',
   'Character': 'Paul Atreides',
   'Profile Path': '/BE2sdjpgsa2rNTFa66f7upkaOP.jpg'},
  {'Name': 'Zendaya',
   'Character': 'Chani',
   'Profile Path': '/3WdOloHpjtjL96uVOhFRRCcYSwq.jpg'},
  {'Name': 'Rebecca Ferguson',
   'Character': 'Jessica',
   'Profile Path': '/lJloTOheuQSirSLXNA3JHsrMNfH.jpg'},
  {'Name': 'Javier Bardem',
   'Character': 'Stilgar',
   'Profile Path': '/IShnFg6ijWhpbu29dFBd9PtqQg.jpg'},
  {'Name': 'Josh Brolin',
   'Character': 'Gurney Halleck',
   'Profile Path': '/sX2etBbIkxRaCsATyw5ZpOVMPTD.jpg'},
  {'Name': 'Austin Butler',
   'Character': 'Feyd-Rautha',
   'Profile Path': '/atdAs4pFGjUQ4m2W8kJYly7N6cC.jpg'},
  {'Name': 'Florence Pugh',
   'Character': 'Princess Irulan',
   'Profile Path': '/6Sjz9teWjrMY9lF2o9FCo4XmoRh.jpg'},
  {'Name': 'Dave Bautista',
   'Character': 'Beast Rabban',
   'Profile Path': '/ymn6iQBJbQZN6BYI60YJDXVP4gF.jpg'},
  {'Name': 'Christopher Walken',
   'Character': 'Emperor',
   'Profile Path': '/ApgDL7nudR9T2GpjCG4vESgymO2.jpg'},
  {'Name': 'Léa Seydoux',
   'Character': 'Lady Margot Fenring',
   'Profile Path': '/1LUzpfSkNluSW8EhdkMaCGRUrTz.jpg'}],
 'Crew': [{'Name': 'Francine Maisler',
   'Job': 'Casting',
   'Department': 'Production'},
  {'Name': 'Mary Parent', 'Job': 'Producer', 'Department': 'Production'},
  {'Name': 'Cale Boyter', 'Job': 'Producer', 'Department': 'Production'},
  {'Name': 'Kim Herbert',
   'Job': 'Executive Producer',
   'Department': 'Production'},
  {'Name': 'Herb Gains',
   'Job': 'Executive Producer',
   'Department': 'Production'},
  {'Name': 'Byron Merritt',
   'Job': 'Executive Producer',
   'Department': 'Production'},
  {'Name': 'Jon Spaihts',
   'Job': 'Executive Producer',
   'Department': 'Production'},
  {'Name': 'Brian Herbert',
   'Job': 'Executive Producer',
   'Department': 'Production'},
  {'Name': 'Thomas Tull',
   'Job': 'Executive Producer',
   'Department': 'Production'},
  {'Name': 'Joshua Grode',
   'Job': 'Executive Producer',
   'Department': 'Production'},
  {'Name': 'Jessica Derhammer',
   'Job': 'Co-Producer',
   'Department': 'Production'},
  {'Name': 'Jessica Derhammer',
   'Job': 'Unit Production Manager',
   'Department': 'Production'},
  {'Name': 'Denis Villeneuve', 'Job': 'Screenplay', 'Department': 'Writing'},
  {'Name': 'Tanya Lapointe', 'Job': 'Producer', 'Department': 'Production'},
  {'Name': 'Dixie Chassay', 'Job': 'Casting', 'Department': 'Production'},
  {'Name': 'Nancy Case',
   'Job': 'Casting Assistant',
   'Department': 'Production'},
  {'Name': 'Tarik Afifi',
   'Job': 'First Assistant Director',
   'Department': 'Directing'},
  {'Name': 'John Harrison',
   'Job': 'Executive Producer',
   'Department': 'Production'},
  {'Name': 'Kim Allison-Hèbert',
   'Job': 'Executive Producer',
   'Department': 'Production'},
  {'Name': 'Richard P. Rubinstein',
   'Job': 'Executive Producer',
   'Department': 'Production'},
  {'Name': 'Patrick McCormick', 'Job': 'Producer', 'Department': 'Production'},
  {'Name': 'Louis Clark',
   'Job': 'Third Assistant Director',
   'Department': 'Directing'},
  {'Name': 'Toby Hefferman',
   'Job': 'First Assistant Director',
   'Department': 'Directing'},
  {'Name': 'Vera Janisch',
   'Job': 'Second Second Assistant Director',
   'Department': 'Directing'},
  {'Name': 'George Max Trummler',
   'Job': 'Third Assistant Director',
   'Department': 'Directing'},
  {'Name': 'Tamás Péter Chipie',
   'Job': 'First Assistant Director',
   'Department': 'Directing'},
  {'Name': 'Denis Villeneuve', 'Job': 'Director', 'Department': 'Directing'},
  {'Name': 'Frank Herbert', 'Job': 'Novel', 'Department': 'Writing'},
  {'Name': 'Jon Spaihts', 'Job': 'Screenplay', 'Department': 'Writing'},
  {'Name': 'Denis Villeneuve', 'Job': 'Producer', 'Department': 'Production'}]}

In [18]:
data = pd.DataFrame.from_dict(data, orient='index').T
data

,Title,Content ID,Type,Poster,Backdrop,Overview,Trailer,Genres,Runtime (minutes),Number of Episodes,Rating,Release Year,Origin Country,Reviews,Recommendations,Cast,Crew
0,Dune: Part Two,693134,movie,/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg,/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg,Follow the mythic journey of Paul Atreides as ...,https://www.youtube.com/watch?v=U2Qp5pL3ovA,"Science Fiction, Adventure",167,1,8.16,2024-02-27,US,[FULL SPOILER-FREE REVIEW @ https://talkingfil...,"[{'Title': 'Dune', 'Poster': '/d5NXSklXo0qyIYk...","[{'Name': 'Timothée Chalamet', 'Character': 'P...","[{'Name': 'Francine Maisler', 'Job': 'Casting'..."